"""Fictional product help articles and author-labeled queries; not product advice."""
from pathlib import Path
from jevector import atomic_json
PAIRS=[
('lost_device','Recover access after a missing second factor','On the sign-in screen choose Use a recovery code and enter one of the one-time codes saved during enrollment. If none remain, start identity recovery and ask a workspace administrator to verify ownership. After verification, enroll a replacement authenticator and invalidate the missing device. Resetting the password alone does not remove the second-factor requirement.','My old phone fell into the sea. I know my password, but the login screen wants a code from that phone. How can I get back in?'),
('password','Replace a forgotten password','Select Forgot password on the sign-in page. Enter the account email and open the reset link within fifteen minutes. Set a new password, then sign in. This changes the password only; a configured second factor is still required.','I still have my authentication app, but I cannot remember the secret I type before the code. What should I do?'),
('email','Move your login address','While signed in, open Account, Email, Change address. Verify the new mailbox and confirm with your current password. Existing workspace memberships are preserved. This procedure does not recover a locked-out account.','I am leaving my employer and losing that mailbox. Can I keep my account but use my personal email for login?'),
('disable_mfa','Turn off the extra sign-in factor','While signed in, open Security, Multi-factor authentication, Disable. Confirm using the current authenticator or a recovery code. Administrators may forbid disabling this setting. This procedure assumes you can already access account settings; it is not a lost-device recovery workflow.','I can sign in normally. How do I stop being asked for an extra code on future logins?'),
('cancel','Stop the next renewal','A billing administrator can open Billing, Subscription, Cancel renewal. Access continues until the prepaid term ends and no future renewal is scheduled. Cancellation does not return previous payments. Refund requests use a separate review process.','Keep what I already paid for, but make sure you do not bill me again next month. Where do I do that?'),
('refund','Ask for a payment reversal','Open Billing, Payment history, select the charge and choose Request refund. Explain the reason and attach supporting details. A billing reviewer checks eligibility within five business days. Approval reverses that charge to the original payment method. This request does not cancel future subscription renewals.','I want last week’s payment returned to my card. I am not asking to stop the subscription. How do I submit that?'),
('annual','Change the billing interval','Open Billing, Plan, Billing interval and select Monthly or Annual. Review the effective date and prorated amount before confirming. The screen shows whether the change begins immediately or at the next renewal.','Can I pay for a year at a time instead of getting a bill every month?'),
('invoice','Retrieve an accounting receipt','A billing administrator opens Billing, Documents, chooses a payment date, and downloads the invoice PDF. The document includes the billed entity, tax lines and transaction reference.','Our bookkeeper needs the PDF showing what we paid and the tax on it. Where is it?'),
('rate_limit','Back off after too many requests','HTTP 429 means the request rate exceeded the account allowance. Read Retry-After, pause new calls for that interval, and add exponential backoff with jitter. Limit concurrent workers and avoid retry storms. A retry does not need a new API key.','My integration works for small batches but gets 429 when I launch many requests together. How should I change the client?'),
('timeout','Investigate calls that wait too long','For requests that exceed the client deadline, log elapsed time and request ID, check service availability, and retry only idempotent operations. Increase the deadline for legitimately long jobs or move them to the asynchronous endpoint. A timeout is distinct from the server explicitly rejecting a request for rate limits.','Sometimes a request just waits until my 30-second deadline expires. There is no 429. How do I diagnose it?'),
('credentials','Fix unauthorized API requests','HTTP 401 indicates missing or invalid credentials. Send the bearer token in the Authorization header, verify the intended environment, and replace revoked or expired tokens. Never place a secret in a query string. A 403 instead concerns authorization to a resource.','Every request says 401 even when I send only one. Which part of authentication should I check?'),
('duplicates','Make webhook consumption idempotent','Store each incoming event ID in a durable table before applying side effects. If the ID already exists, acknowledge the event without applying it again. Return a successful response promptly. Delivery retries can send the same event more than once, so idempotency is required.','One customer action sometimes makes my webhook handler create two orders. How do I prevent the second side effect?'),
('signature','Check who sent a webhook','Read the raw HTTP request bytes and the timestamped signature header. Recompute the HMAC using the endpoint secret and compare it in constant time. Reject mismatches and stale timestamps. Parsing and reserializing JSON before verification changes the signed bytes.','How can my endpoint tell whether an event really came from your service rather than somebody faking a POST?'),
('export','Take a portable copy of workspace records','A workspace owner opens Settings, Data, Export. Choose JSON or CSV and wait for the archive notification. Download the signed link before it expires. Exporting leaves the original workspace and records intact.','I need a copy of all our records for analysis elsewhere, but leave the originals where they are. What is the process?'),
('erase','Erase the account permanently','The account owner opens Settings, Privacy, Erase account and confirms the irreversible request. Sessions are ended and the deletion queue removes records subject to the stated retention policy. Export needed information first; erasure is not a backup operation.','I want the account and its stored records gone permanently, not just a downloaded copy. Where do I request that?'),
('restore','Recover a file from the trash','Open Files, Trash, select the deleted item, and choose Restore. Files remain recoverable for thirty days unless the trash was permanently emptied. Restored files return to their original folder when it still exists.','I accidentally removed a file yesterday. Can I bring it back instead of recreating it?')]
def build():
 docs=[{'id':k,'title':title,'body':body} for k,title,body,q in PAIRS]
 queries=[{'id':f'q{i+1:02}','text':q,'relevant':[k]} for i,(k,title,body,q) in enumerate(PAIRS)]
 queries += [{'id':'q17','text':'How do I undo an accidental removal from the file list?','relevant':['restore']}, {'id':'q18','text':'Where can finance get proof of a completed payment?','relevant':['invoice']}, {'id':'q19','text':'What prevents repeated notifications from causing repeated purchases?','relevant':['duplicates']}, {'id':'q20','text':'Can I keep access until the end of this month without extending the plan?','relevant':['cancel']}]
 return {'version':'support-fixture-1.0','provenance':'Assistant-authored fictional help center; labeled before inference. No real service behavior is claimed.','documents':docs,'queries':queries}
if __name__=='__main__':atomic_json('search_demo/data.json',build())
